<a href="https://colab.research.google.com/github/Divyasri-1323/AIML-LAB/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
fruits=["apple","banana","cherry"]
print(fruits)

['apple', 'banana', 'cherry']


In [2]:
import pandas as pd
fruits=["apple","banana","cherry"]
print(fruits)

['apple', 'banana', 'cherry']


In [3]:
import numpy as np
numbers=np.array([1,2,3,4])
print(numbers)

[1 2 3 4]


In [4]:
import numpy as np
number=np.array([1,2,3])
print(type(number))

<class 'numpy.ndarray'>


In [5]:
import pandas as pd
fruits=["apple","banana","cherry"]
print(type(fruits))

<class 'list'>


In [9]:
import numpy as np
num1=np.array([1,2,3])
num2=np.array([4,5,6])
print(num1*num2)
print(num1/num2)
print(num1**2)
print(num2**2)

[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[16 25 36]


In [14]:
import numpy as np
num1=np.array([1,2,3])
num2=np.array([4,5,6])
result=np.add(num1,num2)
output_text=f"Addition of two:{result}"
print(output_text)

Addition of two:[5 7 9]


In [16]:
import numpy as np
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
sin_x = np.sin(my_array)
print(f"sin({my_array}) = {sin_x}")
log_x = np.log(x)
print(f"log({my_array}) = {log_x}")
log2_x = np.log2(my_array)
print(f"log2({my_array}) = {log2_x}")
exp_x = np.exp(my_array)
print(f"exp({my_array}) = {exp_x}")

sin([1 2 3 4 5]) = [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


NameError: name 'x' is not defined