<a href="https://colab.research.google.com/github/Divyasri-1323/AIML-LAB/blob/main/neural%20netwoks1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
inputs=[1,2,3]
weight=[0.2,0.3,0.5]
bias=2

output = inputs[0]*weight[0]+inputs[1]*weight[1]+inputs[2]*weight[2]+bias
print(output)

4.3


In [15]:
inputs=[0.4,0.3,1,0.8]
weights1=[0.3,0.2,0.1,0.4]
weights2=[0.4,0.1,-0.1,0.2]
weights3=[0.2,0.3,0.4,0.6]
bias1=0.5
bias2=0.2
bias3=0.6

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(output)

[1.1, 0.45000000000000007, 1.65]


In [17]:
import numpy as np
inputs=np.array([0.4,0.3,1,0.8])
weights=np.array([
    [0.3,0.2,0.1,0.4],
    [0.4,0.1,-0.1,0.2],
    [0.2,0.3,0.4,0.6]
])
bias=np.array([0.5,0.2,0.6])
output=np.dot(weights,inputs)+bias
print(output)

[1.1  0.45 1.65]


In [19]:
import numpy as np
def relu(x):
    return np.maximum(0,x)
inputs=np.array([0.4,0.3,1,0.8])
weights=np.array([
    [0.3,0.2,0.1,0.4],
    [0.4,0.1,-0.1,0.2],
    [0.2,0.3,0.4,0.6]
])
bias=np.array([0.5,0.2,0.6])
output=np.dot(weights,inputs)+bias
output1=relu(output)
print(output)


[1.1  0.45 1.65]


In [2]:
import numpy as np
def sigmoid(x):
  return 1 / (1 + np.exp(-x))
def relu(x):
    return np.maximum(0,x)
inputs=np.array([0.4,0.3,1,0.8])
weights=np.array([
    [0.3,0.2,0.1,0.4],
    [0.4,0.1,-0.1,0.2],
    [0.2,0.3,0.4,0.6]
])
bias=np.array([0.5,0.2,0.6])
output=np.dot(weights,inputs)+bias
output1= relu(output)
print(output1)
output2= sigmoid(output)
print(output2)

[1.1  0.45 1.65]
[0.75026011 0.61063923 0.83889105]
